### ISSUE TITLE
continue NOT pass in loop (derp)

### ISSUE THREAD

**Issue by jheidecker** [jheidecker/lemmony#6]
not filtering already subbed communities!

**Comment by drdaeman** [comment]
If I understood what this issue is about correctly, I don't think there's a bug. It should filter. The community is only added to `local_community_id_list` if its not subscribed to. Writing `continue` instead of [`pass` here](https://github.com/jheidecker/lemmony/blob/cbc93d63b050229dd4f9b1846774951f6470fffb/lemmony/cli.py#L109) won't make any difference there, as that conditional is the whole body of the loop.

You probably should rewrite the condition to make it easier to read:
```python
for community in actor_resp.json()['communities']:
    if community['subscribed'] != 'Subscribed':
        local_community_id_list.append(community['community']['id'])
```
(Or something similar if you want to change behavior to e.g. "only unsubscribed" - the snippet above matches the current logic)

**Comment by jheidecker** [comment]
> If I understood what this issue is about correctly, I don't think there's a bug. It should filter. The community is only added to `local_community_id_list` if its not subscribed to. Writing `continue` instead of [`pass` here](https://github.com/jheidecker/lemmony/blob/cbc93d63b050229dd4f9b1846774951f6470fffb/lemmony/cli.py#L109) won't make any difference there, as that conditional is the whole body of the loop.
> 
> You probably should rewrite the condition to make it easier to read:
> 
> ```python
> for community in actor_resp.json()['communities']:
>     if community['subscribed'] != 'Subscribed':
>         local_community_id_list.append(community['community']['id'])
> ```
> 
> (Or something similar if you want to change behavior to e.g. "only unsubscribed" - the snippet above matches the current logic)

PR? :) It's nice getting to say that for a change. No pressure. I am open to all sorts of changes and refactoring. Uber-dev I am not.
